update to support aws provider 4.0

diff --git a/scripts/format-terraform b/scripts/format-terraform
--- a/scripts/format-terraform
+++ b/scripts/format-terraform
@@ -1,4 +1,4 @@
-#! /usr/bin/env bash
+#!/bin/bash
 
 # =================================================================
 #
@@ -12,15 +12,11 @@ set -eu -o pipefail
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 readonly DIR
 
-if ! command -v terraform-docs > /dev/null; then
-  echo "terraform-docs is missing."
+if ! command -v terraform > /dev/null; then
+  echo "terraform is missing."
   exit 1
 fi
 
 pushd "${DIR}/.." > /dev/null
-terraform-docs markdown . > README.md
-echo "<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> TMP_README.md
-cat README.md >> TMP_README.md
-echo "<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> TMP_README.md
-mv TMP_README.md README.md
-popd  > /dev/null
+terraform fmt
+popd > /dev/null
